name: Update Weather Station

on:
  schedule:
    - cron: '0 6 * * *' # Runs at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Forecast Frames
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python plot_weather.py

      - name: Commit and Push
        run: |
          git config --global user.name "WeatherBot"
          git config --global user.email "bot@noreply.github.com"
          
          # Force add the new images (even if they replaced old ones)
          git add images/*.png
          git add index.html
          
          # Commit if changes exist
          git commit -m "Update forecast maps" || echo "No changes"
          git push
