name: Daily Weather Plot

on:
  schedule:
    # Runs at 6:00 AM UTC every day
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows you to run it manually to test

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Needed to push the image back to the repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Weather Map
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python plot_weather.py

      - name: Commit and Push
        run: |
          git config --global user.name 'WeatherBot'
          git config --global user.email 'bot@noreply.github.com'
          git add forecast.png
          git commit -m "Update weather map [skip ci]" || echo "No changes to commit"
          git push
